@startuml
actor User as user
participant App as app
participant PasswordGenerator as pg

user -> app: java -jar ./demo-java-cli.jar generate password
activate app
app -> pg: generatePassword()
activate pg
app <-- pg: return generated password
deactivate pg
user <-- app: show generated password
deactivate app
@enduml