@startuml
'https://plantuml.com/class-diagram

class App {
- PasswordGenerator passwordGenerator

+ {static} void main(String[] args)
- <<constructor>> App(PasswordGenerator passwordGenerator)
- void start(String[] args)
- boolean isValid(String[] args)
- void process(String[] args)
- void showUsage()
- void showGeneratedPassword(String generatedPassword)
}

interface PasswordGenerator {
    +String generatePassword()
}

class PasswordGeneratorImpl {
}

PasswordGenerator <|-- PasswordGeneratorImpl
App *-- PasswordGenerator
@enduml