@startuml
'https://plantuml.com/class-diagram

class App {
    - ArgumentProcessor argumentProcessor
    - Display display
    + {static} void main(String[] args)
    - void start(String[] args)
}

interface ArgumentProcessor {
    + boolean validateArguments(String[] args)
    + void processArguments(String[] args)
}

class ArgumentProcessorImpl {
    - PasswordGenerator passwordGenerator
    - Display display
}

interface Display {
    + void showUsage()
    + void showGeneratedPassword(String generatedPassword)
}

class DisplayImpl {
}

interface PasswordGenerator {
    +String generatePassword()
}

class PasswordGeneratorImpl {
}
ArgumentProcessor <|-- ArgumentProcessorImpl
Display <|-- DisplayImpl
PasswordGenerator <|-- PasswordGeneratorImpl

App *--l ArgumentProcessor
App *--d Display
App *--r PasswordGenerator
@enduml