@startuml
participant App as app
participant ArgumentProcessor as argumentProcessor
participant PasswordGenerator as passwordGenerator
participant Display as display

activate app


app -> argumentProcessor: validate
activate argumentProcessor
app <-- argumentProcessor: true/false
deactivate argumentProcessor

alt#Gold #LightBlue Arguments are valid
    app -> argumentProcessor: process
    activate argumentProcessor
    argumentProcessor -> passwordGenerator: generatePassword
    activate passwordGenerator
    argumentProcessor <-- passwordGenerator: return generated password
    deactivate passwordGenerator
    argumentProcessor -> display: showGeneratedPassword
    activate display
    argumentProcessor <-- display
    deactivate display
    app <-- argumentProcessor
    deactivate argumentProcessor
else #Pink Arguments are not valid
    app -> display: showUsage
    activate display
    app <-- display
    deactivate display
end

deactivate app
@enduml